# Torch Tensor

In [1]:
a = [1.0, 2.0, 1.0]
display(a[0])

a[2] = 3.0
display(a)

1.0

[1.0, 2.0, 3.0]

In [2]:
import torch # <1>
a = torch.ones(3) # <2>

display(a)
display(a[1])
display(float(a[1]))

a[2] = 2.0
display(a)

tensor([1., 1., 1.])

tensor(1.)

1.0

tensor([1., 1., 2.])

In [3]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
display(points)

points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
display(points)

display((float(points[0]), float(points[1])))

tensor([4., 1., 5., 3., 2., 1.])

tensor([4., 1., 5., 3., 2., 1.])

(4.0, 1.0)

In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
display(points)
display(points.shape)
points = torch.zeros(3, 2)
display(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

torch.Size([3, 2])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
display(points)
display(points[0, 1])
display(points[0])

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

tensor(1.)

tensor([4., 1.])

In [6]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
display(points_storage)
display(points_storage[0])
display(type(points_storage))
display(points.storage()[1])

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

4.0

torch.FloatStorage

1.0

In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
display(points)

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
display(second_point.storage_offset())
display(second_point.size())
display(second_point.shape)

2

torch.Size([2])

torch.Size([2])

In [9]:
display(points)
display(points.stride())
display(second_point.stride())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

(2, 1)

(1,)

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
display(points)

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
display(points)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

# Torch Transpose

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
display(points)

points_t = points.t()
display(points_t)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [13]:
display(id(points.storage()) == id(points_t.storage()))
display(points.data_ptr() == points_t.data_ptr())

True

True

In [14]:
display(points)
display(points.stride())

display(points_t)
display(points_t.stride())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

(2, 1)

tensor([[4., 5., 2.],
        [1., 3., 1.]])

(1, 2)

In [15]:
display(points.storage())
display(points_t.storage())

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [16]:
some_t = torch.tensor(range(60)).view(3,4,5).clone()
display(some_t)
display(some_t.shape)
display(some_t.stride())

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

torch.Size([3, 4, 5])

(20, 5, 1)

In [17]:
transpose_t = some_t.transpose(0, 2)
display(transpose_t)
display(transpose_t.shape)
display(transpose_t.stride())

tensor([[[ 0, 20, 40],
         [ 5, 25, 45],
         [10, 30, 50],
         [15, 35, 55]],

        [[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]],

        [[ 2, 22, 42],
         [ 7, 27, 47],
         [12, 32, 52],
         [17, 37, 57]],

        [[ 3, 23, 43],
         [ 8, 28, 48],
         [13, 33, 53],
         [18, 38, 58]],

        [[ 4, 24, 44],
         [ 9, 29, 49],
         [14, 34, 54],
         [19, 39, 59]]])

torch.Size([5, 4, 3])

(1, 5, 20)

In [18]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
display((a.shape, a_t.shape))

a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
display((a.shape, a_t.shape))

(torch.Size([3, 2]), torch.Size([2, 3]))

(torch.Size([3, 2]), torch.Size([2, 3]))

# Torch Contiguous

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()

display(points.is_contiguous())
display(points_t.is_contiguous())

True

False

In [20]:
display(points_t.storage())
display(points_t.stride())

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

(1, 2)

In [21]:
points_t_cont = points_t.contiguous()
display(points_t_cont)
display(points_t_cont.stride())
display(points_t_cont.storage())

tensor([[4., 5., 2.],
        [1., 3., 1.]])

(3, 1)

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [22]:
display((id(points.storage()), id(points_t.storage()), id(points_t_cont.storage()), ))
display((points.data_ptr(), points_t.data_ptr(), points_t_cont.data_ptr()))

(140645265412992, 140645265412992, 140645265412992)

(94611380594176, 94611380594176, 94611339372096)

# Torch Conversion

In [23]:
display(torch.rand(5,6).dtype)
display(torch.ones(10, 2).dtype)
display(torch.zeros(10, 2).dtype)
display(torch.tensor([1, 2]).dtype)

torch.float32

torch.float32

torch.float32

torch.int64

In [24]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

display(double_points)
display(short_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [25]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [26]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [27]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

# Torch Indexing

In [28]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [29]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [30]:
display(points)
display(points.shape)
print()
display(points[None])
display(points[None].shape)
print()
display(points[None][None])
display(points[None][None].shape)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

torch.Size([3, 2])

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

torch.Size([1, 3, 2])

tensor([[[[4., 1.],
          [5., 3.],
          [2., 1.]]]])

torch.Size([1, 1, 3, 2])

In [31]:
display(torch.tensor([[1,2],[3,4]]))
print()
display(torch.tensor([[1,2],[3,4]])[None])
print()
display(torch.tensor([[1,2],[3,4]]).unsqueeze(0))
print()
display(torch.tensor([[1,2],[3,4]]).unsqueeze(1))
print()
display(torch.tensor([[1,2],[3,4]]).unsqueeze(2))

tensor([[1, 2],
        [3, 4]])

tensor([[[1, 2],
         [3, 4]]])

tensor([[[1, 2],
         [3, 4]]])

tensor([[[1, 2]],

        [[3, 4]]])

tensor([[[1],
         [2]],

        [[3],
         [4]]])

In [32]:
display(torch.tensor([[1,2],[3,4]]).shape)
display(torch.tensor([[1,2],[3,4]])[None].shape)
display(torch.tensor([[1,2],[3,4]]).unsqueeze(0).shape)
display(torch.tensor([[1,2],[3,4]]).unsqueeze(1).shape)
display(torch.tensor([[1,2],[3,4]]).unsqueeze(2).shape)

torch.Size([2, 2])

torch.Size([1, 2, 2])

torch.Size([1, 2, 2])

torch.Size([2, 1, 2])

torch.Size([2, 2, 1])

# Torch & Numpy

`from_numpy()` automatically inherits input array dtype. On the other hand, torch.Tensor is an alias for torch.FloatTensor.

Therefore, if you pass int64 array to torch.Tensor, output tensor is float tensor and they wouldn't share the storage. torch.from_numpy gives you torch.LongTensor as expected.

In [33]:
import numpy as np
a = np.arange(10)
ft = torch.Tensor(a)  # same as torch.FloatTensor
it = torch.from_numpy(a)

display(a.dtype)  # == dtype('int64')
display(ft.dtype)  # == torch.float32
display(it.dtype)  # == torch.int64

dtype('int64')

torch.float32

torch.int64

The recommended way to build tensors in Pytorch is to use the following two factory functions: `torch.tensor` and `torch.as_tensor`.

`torch.tensor` always copies the data. For example, `torch.tensor(x)` is equivalent to `x.clone().detach()`.

`torch.as_tensor` always tries to avoid copies of the data. One of the cases where `as_tensor` avoids copying the data is if the original data is a numpy array.

# Torch Saving

In [34]:
points = torch.ones(3, 4)
points_np = points.numpy()
display(points_np)
print()
points = torch.from_numpy(points_np)
display(points)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
torch.save(points, './data_p1ch3/ourpoints.t')
points_load = torch.load('./data_p1ch3/ourpoints.t')
display(points_load)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
with open('./data_p1ch3/ourpoints_file.t','wb') as f:
    torch.save(points, f)
with open('./data_p1ch3/ourpoints_file.t','rb') as f:
    points_read = torch.load(f)
display(points_read)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
import h5py

f = h5py.File('./data_p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
print(dset)
f.close()

<HDF5 dataset "coords": shape (3, 4), type "<f4">


In [38]:
f = h5py.File('./data_p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']

last_points = dset[-2:]
display(last_points)

last_points = torch.from_numpy(dset[-2:])
display(last_points)

f.close()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Torch GPU & _

In [39]:
if torch.cuda.is_available():
    points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

    points_gpu = points.to(device='cuda')
    points_gpu = points.to(device='cuda:0')
    points = 2 * points  # <1>
    points_gpu = 2 * points.to(device='cuda')  # <2>
    points_gpu = points_gpu + 4
    points_cpu = points_gpu.to(device='cpu')
    
    points_gpu = points.cuda()  # <1>
    points_gpu = points.cuda(0)
    points_cpu = points_gpu.cpu()

In [40]:
a = torch.ones(3, 2)
a.zero_()
display(a)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])