## Exercise 1

In [1]:
import torch
a = torch.tensor(list(range(9)))
print((a.size(), a.shape))
print(a.storage())

(torch.Size([9]), torch.Size([9]))
 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]


In [2]:
print(a.storage_offset())
print(a[0].storage_offset())
print(a[1].storage_offset())

0
0
1


In [3]:
print(a.stride())
print(a[0].stride())
print(a[1].stride())

(1,)
()
()


In [4]:
b = a.view(3,3)
print(b)
print(b.storage_offset())
print(b.stride())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
0
(3, 1)


In [5]:
print(b[0].storage_offset())
print(b[1].storage_offset())

0
3


In [6]:
print(id(a) == id(b))
print(id(a.storage()) == id(b.storage()))
print(a.data_ptr()==b.data_ptr())

False
True
True


In [7]:
c = b[1:,1:]
print(c)

tensor([[4, 5],
        [7, 8]])


In [8]:
print(id(c.storage()) == id(b.storage()))
print(c.data_ptr() == b.data_ptr())

True
False


In [9]:
print(c.shape)
print(c.size())

torch.Size([2, 2])
torch.Size([2, 2])


In [10]:
print(c.storage_offset())
print(c.stride())
print(b.stride())
print(a.stride())

4
(3, 1)
(3, 1)
(1,)


## Exercise 2

In [11]:
print(torch.cos(torch.tensor(3.14)))
print(torch.sqrt(torch.tensor(9.0)))

tensor(-1.0000)
tensor(3.)


In [12]:
# torch.cos(a)
# torch.sqrt(a)

In [13]:
print(torch.cos(a.float()))
print(torch.sqrt(a.float()))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])


In [14]:
a_ = a.float()
print(a_)
print(torch.cos_(a_))
print(a_)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])


In [15]:
a_ = a.float()
print(a_)
print(torch.sqrt_(a_))
print(a_)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])
