In [1]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50, linewidth=75)

In [2]:
bikes_numpy = np.loadtxt(
    "./data_p1ch4/bike-sharing-dataset/hour-fixed.csv", 
    dtype=np.float32, 
    delimiter=",", 
    skiprows=1, 
    converters={1: lambda x: float(x[8:10])}) # <1>
bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.0000e+00, 1.0000e+00,  ..., 1.3000e+01, 1.6000e+01],
        [2.0000e+00, 1.0000e+00,  ..., 3.2000e+01, 4.0000e+01],
        ...,
        [1.7378e+04, 3.1000e+01,  ..., 4.8000e+01, 6.1000e+01],
        [1.7379e+04, 3.1000e+01,  ..., 3.7000e+01, 4.9000e+01]])

In [3]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [4]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes

tensor([[[1.0000e+00, 1.0000e+00,  ..., 1.3000e+01, 1.6000e+01],
         [2.0000e+00, 1.0000e+00,  ..., 3.2000e+01, 4.0000e+01],
         ...,
         [2.3000e+01, 1.0000e+00,  ..., 1.7000e+01, 2.8000e+01],
         [2.4000e+01, 1.0000e+00,  ..., 2.4000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.0000e+00,  ..., 1.3000e+01, 1.7000e+01],
         [2.6000e+01, 2.0000e+00,  ..., 1.6000e+01, 1.7000e+01],
         ...,
         [4.6000e+01, 2.0000e+00,  ..., 9.0000e+00, 9.0000e+00],
         [4.7000e+01, 2.0000e+00,  ..., 8.0000e+00, 8.0000e+00]],

        ...,

        [[1.7332e+04, 3.0000e+01,  ..., 4.1000e+01, 4.1000e+01],
         [1.7333e+04, 3.0000e+01,  ..., 2.7000e+01, 2.8000e+01],
         ...,
         [1.7354e+04, 3.0000e+01,  ..., 3.0000e+01, 3.6000e+01],
         [1.7355e+04, 3.0000e+01,  ..., 3.9000e+01, 4.9000e+01]],

        [[1.7356e+04, 3.1000e+01,  ..., 3.0000e+01, 3.4000e+01],
         [1.7357e+04, 3.1000e+01,  ..., 1.3000e+01, 1.9000e+01],
         ...,
         [1.73

In [5]:
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [6]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes

tensor([[[1.0000e+00, 2.0000e+00,  ..., 2.3000e+01, 2.4000e+01],
         [1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00],
         ...,
         [1.3000e+01, 3.2000e+01,  ..., 1.7000e+01, 2.4000e+01],
         [1.6000e+01, 4.0000e+01,  ..., 2.8000e+01, 3.9000e+01]],

        [[2.5000e+01, 2.6000e+01,  ..., 4.6000e+01, 4.7000e+01],
         [2.0000e+00, 2.0000e+00,  ..., 2.0000e+00, 2.0000e+00],
         ...,
         [1.3000e+01, 1.6000e+01,  ..., 9.0000e+00, 8.0000e+00],
         [1.7000e+01, 1.7000e+01,  ..., 9.0000e+00, 8.0000e+00]],

        ...,

        [[1.7332e+04, 1.7333e+04,  ..., 1.7354e+04, 1.7355e+04],
         [3.0000e+01, 3.0000e+01,  ..., 3.0000e+01, 3.0000e+01],
         ...,
         [4.1000e+01, 2.7000e+01,  ..., 3.0000e+01, 3.9000e+01],
         [4.1000e+01, 2.8000e+01,  ..., 3.6000e+01, 4.9000e+01]],

        [[1.7356e+04, 1.7357e+04,  ..., 1.7378e+04, 1.7379e+04],
         [3.1000e+01, 3.1000e+01,  ..., 3.1000e+01, 3.1000e+01],
         ...,
         [3.00

In [7]:
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 17, 24]), (408, 1, 17))

In [8]:
first_day = bikes[:24].long()
first_day[:,9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2,
        2, 2])

In [9]:
bikes[:,9].min(), bikes[:,9].max() 

(tensor(1.), tensor(4.))

In [10]:
weather_onehot = torch.zeros(first_day.shape[0], 4)

In [11]:
weather_onehot.scatter_(
    dim=1, 
    index=first_day[:,9].unsqueeze(1).long() - 1, # <1>
    value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [12]:
torch.cat((bikes[:24], weather_onehot), 1)[:2]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          6.0000,  0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,
          3.0000, 13.0000, 16.0000,  1.0000,  0.0000,  0.0000,  0.0000],
        [ 2.0000,  1.0000,  1.0000,  0.0000,  1.0000,  1.0000,  0.0000,
          6.0000,  0.0000,  1.0000,  0.2200,  0.2727,  0.8000,  0.0000,
          8.0000, 32.0000, 40.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

In [13]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4,
                                   daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [14]:
daily_weather_onehot.scatter_(
    1, daily_bikes[:,9,:].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [15]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)
daily_bikes.shape

torch.Size([730, 21, 24])

In [16]:
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0

In [17]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - temp_min)
                         / (temp_max - temp_min))

In [18]:
temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - torch.mean(temp))
                         / torch.std(temp))

In [19]:
torch.mean(temp, axis=0)

tensor([-0.1493, -0.1903, -0.2268, -0.2609, -0.3012, -0.3216, -0.3290,
        -0.2941, -0.2122, -0.1001,  0.0228,  0.1364,  0.2298,  0.3053,
         0.3587,  0.3770,  0.3606,  0.3068,  0.2358,  0.1480,  0.0676,
        -0.0010, -0.0567, -0.1057])